import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Toaster } from "./_components/ui/sonner";
import Footer from "./_components/footer";
import AuthProvider from "./_providers/auth";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BarberBooking-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning className="dark">
      <body className={`${montserrat.className}`}>
        <AuthProvider>
          <div className="flex h-full flex-col">
            <div className="flex-1"> {children}</div>
            <Footer />
          </div>
        </AuthProvider>
        <Toaster duration={2000} position="bottom-left" style={{}} />
      </body>
    </html>
  );
}
