import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { Toaster } from "./_components/ui/sonner";
import Footer from "./_components/footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BarberBooking-App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning className="dark">
      <body className={`${montserrat.className}`}>
        {children}
        <Toaster duration={2000} position="bottom-left" style={{}} />

        <Footer />
      </body>
    </html>
  );
}
